const KEY='vespera-hud-v1';
const faces=['✕ Ruptura','◇ Vacío','◈ Tensión','◆ Acierto','✦ Triunfo','★ Resonancia'];
const initial=()=>({players:[{name:'Aventurero 1',carne:6,carneMax:6,psique:6,psiqueMax:6,impulso:4,impulsoMax:4,obolos:20,ubicacion:'Valdora',estado:'Estable',consecuencia:'',inventario:'Equipo básico',marcas:''}],history:[]});
let state;try{state=JSON.parse(localStorage.getItem(KEY))||initial()}catch{state=initial()}
if(!Array.isArray(state.players)||!state.players.length||!Array.isArray(state.history))state=initial();
let active=0;
const save=()=>localStorage.setItem(KEY,JSON.stringify(state));
const safe=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const root=document.createElement('div');root.id='vespera-hud';root.innerHTML=`<button id="vh-toggle">⚔ Vespera</button><section id="vh-panel" hidden><header><b>VESPERA RPG HUD</b><button data-action="close">✕</button></header><div class="vh-row"><select id="vh-player"></select><button data-action="add">+ PJ</button><button data-action="delete">− PJ</button></div><div id="vh-fields"></div><hr><b>Caras del Destino</b><div class="vh-row"><label>Caras <input id="vh-count" type="number" min="2" max="5" value="3"></label><button data-action="roll">Lanzar</button></div><div id="vh-result">Sin tiradas</div><div class="vh-row"><button data-action="copy">Copiar estado</button><button data-action="export">Exportar</button><button data-action="import">Importar</button></div><input id="vh-file" type="file" accept="application/json,.json" hidden><small>Guardado local. La IA no recibe cambios automáticamente.</small></section>`;document.body.appendChild(root);
const $=q=>root.querySelector(q);
const specs=[['carne','Carne','number'],['carneMax','Máximo Carne','number'],['psique','Psique','number'],['psiqueMax','Máximo Psique','number'],['impulso','Impulso','number'],['impulsoMax','Máximo Impulso','number'],['obolos','Óbolos','number'],['ubicacion','Ubicación','text'],['estado','Estado','text'],['consecuencia','Consecuencia','textarea'],['inventario','Inventario','textarea'],['marcas','Marcas','textarea']];
function render(){const p=state.players[active];$('#vh-player').innerHTML=state.players.map((x,i)=>`<option value="${i}" ${i===active?'selected':''}>${safe(x.name)}</option>`).join('');$('#vh-fields').innerHTML=`<label>Nombre<input data-key="name" value="${safe(p.name)}"></label>`+specs.map(([key,label,type])=>{const val=safe(p[key]);const bar=['carne','psique','impulso'].includes(key);const pct=bar?Math.max(0,Math.min(100,100*Number(p[key])/(Number(p[key+'Max'])||1))):0;return `<label>${label}${type==='textarea'?`<textarea data-key="${key}">${val}</textarea>`:`<input data-key="${key}" type="${type}" ${type==='number'?'min="0"':''} value="${val}">`}${bar?`<span class="vh-meter"><i class="${key}" style="width:${pct}%"></i></span>`:''}</label>`}).join('')}
function summary(){return state.players.map(p=>`[${p.name}]\nCarne ${p.carne}/${p.carneMax} | Psique ${p.psique}/${p.psiqueMax} | Impulso ${p.impulso}/${p.impulsoMax}\nÓbolos: ${p.obolos}\nUbicación: ${p.ubicacion}\nEstado: ${p.estado}\nConsecuencia: ${p.consecuencia}\nInventario: ${p.inventario}\nMarcas: ${p.marcas}`).join('\n\n')+'\n\nTiradas recientes:\n'+state.history.slice(0,5).join('\n')}
$('#vh-toggle').onclick=()=>{$('#vh-panel').hidden=!$('#vh-panel').hidden};$('#vh-player').onchange=e=>{active=Number(e.target.value);render()};$('#vh-fields').addEventListener('change',e=>{const k=e.target.dataset.key;if(!k)return;state.players[active][k]=e.target.type==='number'?Math.max(0,Number(e.target.value)||0):e.target.value;save();render()});
root.addEventListener('click',async e=>{const a=e.target.closest('[data-action]')?.dataset.action;if(!a)return;if(a==='close')$('#vh-panel').hidden=true;if(a==='add'){state.players.push({...initial().players[0],name:`Aventurero ${state.players.length+1}`});active=state.players.length-1;save();render()}if(a==='delete'&&state.players.length>1&&confirm('¿Eliminar personaje?')){state.players.splice(active,1);active=0;save();render()}if(a==='roll'){const n=Math.max(2,Math.min(5,Number($('#vh-count').value)||3));const rolls=new Uint32Array(n);crypto.getRandomValues(rolls);const result=Array.from(rolls,x=>faces[x%6]);const line=`${new Date().toLocaleTimeString()} · ${result.join(' | ')}`;state.history.unshift(line);state.history=state.history.slice(0,40);save();$('#vh-result').textContent=line}if(a==='copy'){try{await navigator.clipboard.writeText(summary());$('#vh-result').textContent='Estado copiado. Pégalo en el chat.'}catch{$('#vh-result').textContent='No se pudo copiar: revisa permisos.'}}if(a==='export'){const blob=new Blob([JSON.stringify(state,null,2)],{type:'application/json'});const url=URL.createObjectURL(blob);const link=document.createElement('a');link.href=url;link.download='vespera-save.json';link.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}if(a==='import')$('#vh-file').click()});
$('#vh-file').addEventListener('change',async e=>{try{const v=JSON.parse(await e.target.files[0].text());if(!Array.isArray(v.players)||!v.players.length||!Array.isArray(v.history))throw Error('Formato inválido');state=v;active=0;save();render()}catch(err){alert('Error importando: '+err.message)}e.target.value=''});render();
